### ISSUE TITLE
Supprot for Scene Editing

### ISSUE THREAD

**Issue by Sharpiless** [JOP-Lee/READ#10]
Wonderful Job, does the current code support editing?

**Comment by JOP-Lee** [comment]
Hello, the current version supports manual editing of the point cloud. Without retraining, the rendered scene will be changed accordingly

**Comment by Gatsby23** [comment]
> Hello, the current version supports manual editing of the point cloud. Without retraining, the rendered scene will be changed accordingly

From the video, I know we can remove some cars by removing the point cloud. But can we add some points to generate the new car that haven't seen before？

**Comment by X-WhyY** [comment]
> Hello, the current version supports manual editing of the point cloud. Without retraining, the rendered scene will be changed accordingly

Hello, how can I edit the point cloud manually? Is there any tool for that?

**Comment by JOP-Lee** [comment]
> > Hello, the current version supports manual editing of the point cloud. Without retraining, the rendered scene will be changed accordingly
> 
> Hello, how can I edit the point cloud manually? Is there any tool for that?

@X-WhyY Like metashape, blender, cloudcompare. Find the coordinates of the car and move the car. Or use the script to detect the location of the car in the point cloud and change the location

**Comment by JOP-Lee** [comment]
> > Hello, the current version supports manual editing of the point cloud. Without retraining, the rendered scene will be changed accordingly
> 
> From the video, I know we can remove some cars by removing the point cloud. But can we add some points to generate the new car that haven't seen before？



> > Hello, the current version supports manual editing of the point cloud. Without retraining, the rendered scene will be changed accordingly
> 
> From the video, I know we can remove some cars by removing the point cloud. But can we add some points to generate the new car that haven't seen before？

Sorry, we only tried to move cars in the same scene,  it might not work well if we generate cars that haven't been seen before

**Comment by rockywind** [comment]
Hi,
How can change the car's location using the script?



> > > Hello, the current version supports manual editing of the point cloud. Without retraining, the rendered scene will be changed accordingly
> > 
> > 
> > Hello, how can I edit the point cloud manually? Is there any tool for that?
> 
> @X-WhyY Like metashape, blender, cloudcompare. Find the coordinates of the car and move the car. Or use the script to detect the location of the car in the point cloud and change the location

**Comment by WoodwindHu** [comment]
Hi, I try to remove a car from the scene, but it turned out this error:
'''
RuntimeError: Error(s) in loading state_dict for PointTexture:
	size mismatch for texture_: copying a param with shape torch.Size([1, 8, 2547322]) from checkpoint, the shape in current model is torch.Size([1, 8, 2543402]).
'''
It seems like the model shape should be same to the point cloud size. 
How can I edit the point cloud correctly?
