### ISSUE TITLE
ValueError: string is not a file: pointcloud.ply

### ISSUE THREAD

**Issue by bobd988** [JOP-Lee/READ#14]
When I ran training during the pointcloud.ply load stage, it gave error in this function

    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: pointcloud.ply

I trace to this function

def import_model3d(model_path, uv_order=None, is_mesh=False):
    data = trimesh.load(model_path)  

in load.py it seems not able to get file_type for  pointcloud.ply 
....
        else:
            if '{' in file_obj:
                # if a dict bracket is in the string, its probably a straight
                # JSON
                file_type = 'json'
            elif 'https://' in file_obj or 'http://' in file_obj:
                # we've been passed a URL, warn to use explicit function
                # and don't do network calls via magical pipeline
                raise ValueError(
                    'use load_remote to load URL: {}'.format(file_obj))
            **_elif file_type is None:
                raise ValueError('string is not a file: {}'.format(file_obj))_**

The file  path for  pointcloud.ply is correct.

**Comment by JOP-Lee** [comment]
May I ask if your version of pytorch etc. is the same as described in this document?
