### ISSUE TITLE
question about camera.xml

### ISSUE THREAD

**Issue by donjiaking** [JOP-Lee/READ#16]
Hi, I wonder the format of transform in `camera.xml` is "camera to world" or "world to camera", and it is in opengl or opencv coordinate system? Thanks very much.

**Comment by JOP-Lee** [comment]
Hi, please refer to the setting of metashape

**Comment by h8c2** [comment]
hi, it's "camera to world"  and opencv coordinate system? i am not familiar with metashape and I am not sure if it is right.
