### ISSUE TITLE
What's the setting of metashape Align photo on the kitti pointcloud data?

### ISSUE THREAD

**Issue by Kanon777** [JOP-Lee/READ#18]
I tried to run Align Photos on the kitti dataset to reproduce the result, but found that the pointcloud generated by metashape is much sparser and lower quality than the pointcloud provided in this repo. I guess this may caused by the difference of settings in the metashape software, so could you please provide the detail settings of metashape align photo that produce the point cloud？

**Comment by Fllacsaa** [comment]
Same question here @JOP-Lee

**Comment by shuhangz** [comment]
You can try 'build dense cloud' in the Metashape after the 'align photo' is finished. The step of  'align photo' just build a sparse point cloud with SfM. The 'build dense cloud' performs the dense image matching in MVS. 
Detailed instructions can be referenced here: https://agisoft.freshdesk.com/support/solutions/articles/31000152092

**Comment by JOP-Lee** [comment]
> You can try 'build dense cloud' in the Metashape after the 'align photo' is finished. The step of 'align photo' just build a sparse point cloud with SfM. The 'build dense cloud' performs the dense image matching in MVS. Detailed instructions can be referenced here: https://agisoft.freshdesk.com/support/solutions/articles/31000152092

 Exactly! @Fllacsaa @Kanon777
