### ISSUE TITLE
Procedure for custom dataset training

### ISSUE THREAD

**Issue by vinodrajendran001** [JOP-Lee/READ#22]
Hi,

I would like to train from scratch using my own dataset. 

Can you pls provide details on what are the inputs required and how to start the training?

Thanks.

**Comment by vinodrajendran001** [comment]
Thanks @JOP-Lee for the the info. Do you have any small dataset (may be couple of images) with their corresponding camera.xml and pointcloud.ply? If so, could you please share it. I would like to visualize those and generate a large scale data for my usecase.

**Comment by JOP-Lee** [comment]
[jiuzhai.zip](https://github.com/JOP-Lee/READ/files/10703442/jiuzhai.zip)

@vinodrajendran001

**Comment by h8c2** [comment]
Hi, I would like to ask about the coordinate definition of the view matrix since I don't want to use metashape to get the poses. Could you give me some suggestions?
