### ISSUE TITLE
proj_matrix was not set

### ISSUE THREAD

**Issue by vinodrajendran001** [JOP-Lee/READ#31]
Hi,

I'm trying to reproduce the results for kitti dataset with the ```headless mode``` but I am getting the following error

![image](https://user-images.githubusercontent.com/5783246/224287166-fefe84d2-242e-4888-a08a-d795066dca72.png)

May I know how to resolve it?

Thanks.

**Comment by JOP-Lee** [comment]
@Sylvia6

**Comment by wuzuyin** [comment]
> @Sylvia6

what do you mean?

**Comment by Sylvia6** [comment]
如果是在headless的模式下，在训练时应该不会在dynamic.py的数据集类中使用OpenGL实现光栅化，而是直接将input_的结果初始化为{}，并在模型推理时直接调用MyRender实现的渲染器进行光栅化（这么写的目的是为了提高光栅化的并行效率，通过Tensor加速，否则会在get_item中每次都执行单图的光栅化，效率较低）。下面是具体的代码细节：


<img width="940" alt="image" src="https://user-images.githubusercontent.com/32163681/225509616-e1edde46-5379-48c7-8f24-2734d45191c1.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/32163681/225510839-82d30e3e-a942-4ff6-b62c-94158cb6241f.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/32163681/225509919-64dd1a30-8f6a-49c8-8007-d812ba6c6eaa.png">

**Comment by Sylvia6** [comment]
If in the headess mode, during training, you should not use OpenGL in `dynamic.py` to realize point rasterization. Instead,  the code will set `input_` to value {} (which will be calculated by out implemented `renderer` in `train.py`）. In this way, we can avoid rasterization  perfomed  every time in the ` __getitem__` , thus gain acceleration.
Here's is the specific code details:

In `READ/src/READ/datasets/dynamic.py`:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/32163681/225511709-d1d0a20f-a606-4611-8850-5af34f856552.png">

While in `READ/src/train.py`:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/32163681/225511571-0b2d82e5-b18d-4fa8-a1d3-7f84b1696cfb.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/32163681/225511614-4df7718a-64de-40f6-8f25-c8deaff8599c.png">

**Comment by Sylvia6** [comment]
@wuzuyin @vinodrajendran001  Would you please take a look at headless mode, is  the code related to `headless` args works?
