### ISSUE TITLE
About the meaning of proj_matrix

### ISSUE THREAD

**Issue by Tsianmy** [JOP-Lee/READ#36]
Hi, I wonder what does proj_matrix do to the points (especially col 3 and col 4) and why do not use intrinsic matrix to project the points directly
proj:
2 * fx / w,             0,                              1 - 2 * cx / w,                0
             0, 2 * fy / h,                              2 * cy / h - 1,                0
             0,             0,  (zfar + znear) / (znear - zfar), 2 * zfar * znear / (znear - zfar)
             0,             0,                                               -1,                0

**Comment by Sylvia6** [comment]
We need to ajust the intrinstics matrix into the OpenGL format（using the ndc coordinates）, the more infomations you can read from [here](http://www.songho.ca/opengl/gl_projectionmatrix.html), note in `GL_PROJECTION` part
