### ISSUE TITLE
How to Combine with Nerf?

### ISSUE THREAD

**Issue by xiepeter** [JOP-Lee/READ#39]
It seems that the pipeline is neural rendering with classic rasterization procedure and optimization on the memory & GPU. It is great job! I am wondering if it is possible to combine with nerf idea?because it appears to be hard if doing sampling and calculating density or RGB. Is it possible to build Grid-like(sparse voxel ) structure in READ?  or get some idea like block-nerf? thank u very much~~

**Comment by JOP-Lee** [comment]
Good idea, in fact we are also thinking about how to integrate Nerf, if you have any ideas, we can discuss or collaborate together.
