### ISSUE TITLE
about pointcloud input

### ISSUE THREAD

**Issue by smithrowe10** [JOP-Lee/READ#46]
I want to ask if there was no pointcloud "xyz" information input to network, only it's size?

**Comment by Sylvia6** [comment]
I agree with your viewpoint @zzxxtt , in our READ method, it's true that the point "xyz" is just used for rasterization. By the way, the index of the point is the key to obtaining descriptors value, resulting the viewpoint-related descriptor maps, which are the input of our neural rendering network.
