### ISSUE TITLE
During scene training, whether to divide into multiple segments, or input all frames together

### ISSUE THREAD

**Issue by MaxChanger** [JOP-Lee/READ#7]
Hello, in your arxiv version, the lengths of several sequences of KITTI are mentioned, which are  3560 frames, 819 frames, and 1584 frames in Residential, Road, and City scenes.

And in Sec3.5 and Figure 5, "To account for the large scale driving scene, we propose a scene stitching method that is able to concatenate multiple scenes and update a block locally."

I want to confirm, for example, is the scene of 3560 frames divided into small blocks, each block is trained separately, and then spliced, or is the 3560 frame data directly input?

In addition, in the `camera.xml` you provided, there are `<partition>` tags, which contains the corresponding `<camera_ids>`. Is this the basis for dividing the training segments? But I see that this `camera.xml` file seems to be load only in the viewer stage?

**Comment by JOP-Lee** [comment]
Hi, The default is training for the entire scene. If there are multiple scenarios, they are trained separately. Please see the ablation experiment in the paper.
