### ISSUE TITLE
There are no points in the sky, how to generate reasonable colors?

### ISSUE THREAD

**Issue by MaxChanger** [JOP-Lee/READ#8]
Congratulations to the article for being accepted.
I have a small question about how to generate the color of the sky. Because SfM+MVS does not generate points of the sky, there will be no corresponding points (features) projected onto the image after rasterization.
I want to know how the network is reasonably predicted and supervised here? 
Thank you~

**Comment by JOP-Lee** [comment]
The point cloud projected onto the current frame learns from the RGB image(GT) and then fills in the empty value of the point cloud through the fusion of same-scale and different-scale features in the rendering network.

**Comment by MaxChanger** [comment]
Thanks, but I am confused about "fills in the empty value of the point cloud through the fusion of same-scale and different-scale ...".

There are no points in the sky area in the image, and there is no corresponding point in the sky in any image size(scale). How to fill them according to different scales?

**Comment by JOP-Lee** [comment]
I don't understand why there are no points in the sky area of the image

**Comment by MaxChanger** [comment]
Hi, as the paper said, the point cloud is obtained by SfM+MVS (Metashape). The part of the sky cannot be obtained by SfM+MVS, because the sky is actually infinite and cannot be represented by the point cloud.

**Comment by JOP-Lee** [comment]
yes, the sky area is not included in the point cloud but is included in the image

**Comment by MaxChanger** [comment]
According to my understanding, in the first step, the features of the point cloud are rasterized to a multi-scale image, and the pixel corresponding to the sky area in the image should be empty, because the point cloud does not contain sky points. This is true even at multiple image sizes or scales. So I don't understand why "fills in the empty value of the point cloud through the fusion of same-scale and different-scale features" could work.

And, I don't know how the network learns the mapping between sky color and point cloud features.
